name: Run Main.py

on:
  schedule:
    - cron: '0 0 * * 1' # Runs at 12:00 AM every Monday

jobs:
  run_main_py:
    name: Run Main.py
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: pip install -r requirements.txt 

    - name: Run main.py
      run: python main.py
