name: Run Main.py

on:
  schedule:
    - cron: '0 0 * * 1,2'
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - name: checkout repo content
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
     
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
      - name: run script
        run: python main.py
