name: Test

on:
  workflow_dispatch:
    inputs:
      run-scraper:
        description: 'Run'
        required: true


jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - name: checkout repo content
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
     
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
      - name: run script
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.email "iyi.obiechina@gmail.com"
          git config --global user.name "obie-china"
          git add .
          git commit -m "Updated data"
          git push
